# search:36_invers_pairs.o
# 	g++ -o inverse_pairs 36_invers_pairs.o
# 36_invers_pairs.o:36_invers_pairs.cpp
# 	g++ -c 36_invers_pairs.cpp
# clean:
# 	rm *~ *.o

heap_sort:heap_sort.o
	g++ -o heap_sort heap_sort.o
heap_sort.o:heap_sort.cpp
	g++ -c heap_sort.cpp
clean:
	rm *~ *.o
