# search:36_invers_pairs.o
# 	g++ -o inverse_pairs 36_invers_pairs.o
# 36_invers_pairs.o:36_invers_pairs.cpp
# 	g++ -c 36_invers_pairs.cpp
# clean:
# 	rm *~ *.o

square_root:square_root.o
	g++ -o square_root square_root.o
square_root.o:square_root.cpp
	g++ -c square_root.cpp
clean:
	rm *~ *.o
