# search:36_invers_pairs.o
# 	g++ -o inverse_pairs 36_invers_pairs.o
# 36_invers_pairs.o:36_invers_pairs.cpp
# 	g++ -c 36_invers_pairs.cpp
# clean:
# 	rm *~ *.o

rotate_str_split:rotate_str_split.o
	g++ -o rotate_str_split rotate_str_split.o
rotate_str_split.o:rotate_str_split.cpp
	g++ -c rotate_str_split.cpp
clean:
	rm *~ *.o
