# search:36_invers_pairs.o
# 	g++ -o inverse_pairs 36_invers_pairs.o
# 36_invers_pairs.o:36_invers_pairs.cpp
# 	g++ -c 36_invers_pairs.cpp
# clean:
# 	rm *~ *.o

badhorse:badhorse.o
	g++ -o badhorse badhorse.o
badhorse.o:badhorse.cpp
	g++ -c badhorse.cpp
clean:
	rm *~ *.o
